# Generated by Django 2.2.5 on 2019-11-09 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='W_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField()),
                ('ValidTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField(blank=True, null=True)),
                ('MachineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Washer')),
            ],
        ),
        migrations.CreateModel(
            name='D_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UserId', models.IntegerField()),
                ('ValidTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField(blank=True, null=True)),
                ('MachineId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Dryer')),
            ],
        ),
    ]
