# Generated by Django 2.2.5 on 2019-11-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='D_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MachineId', models.IntegerField(default=0)),
                ('UserId', models.IntegerField()),
                ('ValidTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='W_Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MachineId', models.IntegerField(default=0)),
                ('UserId', models.IntegerField()),
                ('ValidTime', models.DateTimeField()),
                ('EndTime', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
