# Generated by Django 2.2.5 on 2019-11-11 10:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d_book',
            name='MachineId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Dryer'),
        ),
        migrations.AlterField(
            model_name='d_book',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='w_book',
            name='MachineId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='main.Washer'),
        ),
        migrations.AlterField(
            model_name='w_book',
            name='UserId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
