# Generated by Django 2.2.5 on 2019-11-19 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='d_book',
            name='UserId',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='w_book',
            name='UserId',
            field=models.CharField(max_length=9),
        ),
    ]
