# Generated by Django 2.2.5 on 2019-11-15 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dryer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Place', models.CharField(choices=[('1', '308관 남자'), ('2', '309관 남자'), ('3', '308관 여자'), ('4', '309관 여자')], max_length=10)),
                ('Number', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Washer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Place', models.CharField(choices=[('1', '308관 남자'), ('2', '309관 남자'), ('3', '308관 여자'), ('4', '309관 여자')], max_length=10)),
                ('Number', models.IntegerField(default=1)),
            ],
        ),
    ]
