# Generated by Django 2.2.5 on 2019-11-15 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dryer',
            name='Place',
            field=models.CharField(choices=[(1, '308관 남자'), (2, '309관 남자'), (3, '308관 여자'), (4, '309관 여자')], max_length=10),
        ),
        migrations.AlterField(
            model_name='washer',
            name='Place',
            field=models.CharField(choices=[(1, '308관 남자'), (2, '309관 남자'), (3, '308관 여자'), (4, '309관 여자')], max_length=10),
        ),
    ]
